server:
  port: 9010

spring:
  application:
    name: "ServicioPedidos"

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}

  datasource:
    url: jdbc:h2:file:c:/h2/bbdd_cloud_pedidos
    driverClassName: org.h2.Driver
    username: sa
    password: 
        
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect        

    
#bbdd:
#  url: noseque
#  username: fistro  
#  password: picaporte    
    