
server:
  port: 9000

spring:
  application:
    name: "ServicioClientes"

  cloud:
    consul:
      host: ${CONSUL_IP:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instanceId: ${spring.application.name}:${random.value}

  datasource:
    url: jdbc:h2:file:c:/h2/bbdd_cloud_clientes
    driverClassName: org.h2.Driver
    username: sa
    password: 
        
  jpa: 
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect        

