spring:
  application:
    name: "ServicioProductos_CQRS_Query"
  main:
    web-application-type: none

  #mongodb:
  #  embedded:
  #  version: 3.5.5

  data.mongodb.host: localhost
  data.mongodb.port: 27017
  data.mongodb.database: productos_event_sourcing

kafka:
  direccion: localhost:9092
  topic:
    nombre: topic-productos-cqrs
    grupo: "consumer-productos"