server:
  port: 9000

spring:
  application:
    name: "ServicioClientes"
    
  config:
    import: consul:localhost:8500           

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
      config:
        enabled: true
        fail-fast: true
        #'config' es el valor por defecto'
        prefix: config         
        watch:
          enabled: true
          delay: 10000  
        
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect     

  datasource:
    #url: ${spring.datasource.url}
    #url: ${bbdd.url}
    driverClassName: org.h2.Driver
    username: sa
    #username: ${spring.datasource.username}
    #password: ${spring.datasource.password}
    password:    
    




  
