server:
  port: 9020
  tomcat:
    threads:
      max: 6

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 10
        waitDurationInOpenState: 10s #Cuidado que sin la 's' son milisegundos 
        permittedNumberOfCallsInHalfOpenState: 5
        #recordExceptions:
         #- org.springframework.web.client.HttpServerErrorException      
  instances:
    gestorProductos-buscarProductoYCalificaciones:
      baseConfig: default    

spring:
  application:
    name: "ServicioProductos"
    
  config:
    import: consul:localhost:8500       
  
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
      config:
        enabled: true
        fail-fast: true
        watch:
          enabled: true
          delay: 5000  

  #datasource:
  #  url: jdbc:h2:file:c:/h2/bbdd_cloud_productos
  #  driverClassName: org.h2.Driver
  #  username: sa
  #  password:
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect